// Mermaid.js - v10.9.1
// Copyright (c) 2014 - 2022 Knut Sveidqvist
// Licensed under the MIT License
// https://github.com/mermaid-js/mermaid
//
// This module provides embedded Mermaid.js library and initialization code
// for rendering diagrams from markdown code blocks with the `mermaid` language tag.

/// Mermaid.js library (minified)
///
/// This constant contains the complete Mermaid.js library loaded from:
/// https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
///
/// The library is distributed under the MIT License and is embedded here
/// to provide offline diagram rendering capability.
pub const MERMAID_JS: &str = include_str!("../templates/mermaid.min.js");

/// Mermaid initialization script
///
/// This script initializes Mermaid with secure default settings and targets
/// code blocks with `lang="mermaid"` attribute (generated by comrak for
/// markdown code blocks with `mermaid` language tag).
///
/// Configuration:
/// - `startOnLoad: true` - Automatically render diagrams on page load
/// - `theme: 'default'` - Use the default Mermaid theme
/// - `securityLevel: 'strict'` - Prevent script execution in diagrams
pub const MERMAID_INIT: &str = r###"<script>
/* Mermaid.js Initialization */
document.addEventListener('DOMContentLoaded', function() {
  mermaid.initialize({
    startOnLoad: true,
    theme: 'default',
    securityLevel: 'strict'
  });

  // Target pre blocks with lang="mermaid" attribute (comrak's output format)
  document.querySelectorAll('pre[lang="mermaid"]').forEach(function(pre) {
    const codeBlock = pre.querySelector('code');
    if (!codeBlock) return;

    const diagramText = codeBlock.textContent;

    // Create a div for the mermaid diagram
    const mermaidDiv = document.createElement('div');
    mermaidDiv.className = 'mermaid';
    mermaidDiv.textContent = diagramText;

    // Replace the pre/code block with the mermaid div
    pre.parentNode.replaceChild(mermaidDiv, pre);
  });

  // Re-run mermaid to render the diagrams
  mermaid.init(undefined, document.querySelectorAll('.mermaid'));
});
</script>"###;

/// Complete Mermaid.js script tags for HTML inclusion
///
/// This combines the Mermaid library and initialization script with proper
/// license attribution in HTML comments.
pub fn mermaid_scripts() -> String {
    format!(
        r###"<!-- Mermaid.js | MIT License | Copyright (c) 2014-2022 Knut Sveidqvist -->
<script>
{}
</script>
{}"###,
        MERMAID_JS,
        MERMAID_INIT
    )
}
